# Generated by Django 3.2 on 2021-05-13 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BS', 'Brass Plan'), ('BP', 'Bronze Plan'), ('SP', 'Silver Plan'), ('GP', 'Gold Plan')], max_length=3)),
                ('label', models.CharField(choices=[('ASP', 'A Starter Pack'), ('MP', 'Most Popular'), ('INV', 'Invest More, Earn More'), ('AHF', 'Higher Features You Will Need')], max_length=3)),
                ('max_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('to_pay', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('description1', models.CharField(max_length=30)),
                ('description2', models.CharField(max_length=30)),
                ('description3', models.CharField(max_length=30)),
                ('description4', models.CharField(max_length=30)),
                ('description5', models.CharField(max_length=30)),
                ('description6', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='core.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
