# Generated by Django 3.2 on 2021-05-03 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BP', 'Baby Plan'), ('AP', 'Advanced Plan'), ('LP', 'Luxury Plan'), ('LgP', 'Legend Plan')], max_length=3)),
                ('label', models.CharField(choices=[('DAM', 'Dedicated Account Manager'), ('SAM', 'Senior Account Manager'), ('PRM', 'Personal Relational Manager')], max_length=3)),
                ('max_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('to_pay', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('description1', models.CharField(max_length=30)),
                ('description2', models.CharField(max_length=30)),
                ('description3', models.CharField(max_length=30)),
                ('description4', models.CharField(max_length=30)),
                ('description5', models.CharField(max_length=30)),
                ('description6', models.CharField(max_length=30)),
                ('description7', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='core.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
